// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: licenses.sql

package db

import (
	"context"
)

const insertLicense = `-- name: InsertLicense :one
INSERT INTO "licenses" (product, user, credentials)
VALUES (?, ?, ?)
RETURNING id
`

type InsertLicenseParams struct {
	Product     string
	User        int64
	Credentials string
}

func (q *Queries) InsertLicense(ctx context.Context, arg InsertLicenseParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertLicense, arg.Product, arg.User, arg.Credentials)
	var id int64
	err := row.Scan(&id)
	return id, err
}
