// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import ()

type Licenses struct {
	ID          int64
	User        int64
	Product     string
	Credentials string
}

type Users struct {
	ID    int64
	Email string
}
